Layout/LineLength:
  Max: 200
Metrics/ClassLength:
  Max: 2000
Metrics/MethodLength:
  Max: 200
Metrics/BlockLength:
  Max: 50
Metrics/AbcSize:
  Max: 100
Metrics/ParameterLists:
  Max: 10
Metrics/CyclomaticComplexity:
  Max: 30
Metrics/PerceivedComplexity:
  Max: 30
Style/Documentation:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
